version: '3'
services:
### Servidor Web
    nginx: 
        build: 
            dockerfile: nginx.dockerfile
            context: .
        container_name: nginx
#        volumes:
#            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"
        links:
            - php
        networks:
            - redekabum     

### Aplicação
    php:
        build: 
            dockerfile: dockerfile
        container_name: php
        build: .
        volumes: 
            - ./code:/code
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal
        links:
            - mysql
        networks:
            - redekabum     

### BD da Aplicação
    mysql:
         container_name: mysql
         image: mysql:latest
         ports:
            - "3306:3306"
         environment: 
            - MYSQL_ROOT_PASSWORD=password
         networks:
            - redekabum    

### Monitoramento 
    grafana:
         build: 
            dockerfile: grafana.dockerfile
            context: .
         container_name: grafana
         image: grafana/grafana
         restart: on-failure
         ports:
            - "3000:3000"
         networks:
            - redekabum    
         volumes:
            - ./srv/docker/grafana/data:/var/lib/grafana
            - /etc/timezone:/etc/timezone:ro 

### Dependencia Graylog
    mongodb:
         container_name: mongo
         image: mongo:3
         networks:
            - redekabum 

### Dependencia Graylog  
    elasticsearch:
         container_name: elasticsearch
         image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
         environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
         networks:
            - redekabum 

    graylog:
         container_name: graylog
         image: graylog/graylog:3.3
         environment:
            ### Alterar senha
            - GRAYLOG_PASSWORD_SECRET=teste123
            ### Password: admin
            - GRAYLOG_ROOT_PASSWORD_SHA2=admin
            - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9001/
         links:
            - mongodb:mongo
            - elasticsearch
         depends_on:
            - mongodb
            - elasticsearch
         ports:
      ### Graylog web interface and REST API
            - 9001:9001
      ### Syslog TCP
            - 1514:1514
      ### Syslog UDP
            - 1514:1514/udp
      ### GELF TCP
            - 12201:12201
      ### GELF UDP
            - 12201:12201/udp
         networks:
            - redekabum 

###Rede da infraestrutura em modo bridge
networks:
    redekabum:
        driver: bridge   
